/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jnidemo_jnitest_JniTest */

#ifndef _Included_com_example_jnidemo_jnitest_JniTest
#define _Included_com_example_jnidemo_jnitest_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jnidemo_jnitest_JniTest
 * Method:    getNativeString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jnidemo_jnitest_JniTest_getNativeString
  (JNIEnv *, jclass);

/*
 * Class:     com_example_jnidemo_jnitest_JniTest
 * Method:    getAddResult
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_jnidemo_jnitest_JniTest_getAddResult
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
